apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-base-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: base-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: base-app
    spec:
      containers:
        - image: orobtsovv/base-app
          name: base-app
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /base-app/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /base-app/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 3
          env:
            - name: FEATURE_FLAG_SERVICE_HOST
              value: "http://feature-service"
