apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-feature-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feature-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: feature-service
    spec:
      containers:
        - image: orobtsovv/feature-service
          name: feature-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-db
                  key: db-password
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-db
                  key: db-user
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-env
                  key: DB_HOST
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: config-env
                  key: DB_NAME

