apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liquibase-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: liquibase-pv